version: '3'

services:
  status:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - LOG_LEVEL=debug
    volumes:
      - .:/srv
    restart: always
  redis:
    image: redis:4.0-alpine
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: